export default {
	name: "en",
	displayName: "English",
	dateTimeFormat: {
		AMDesignator: "AM",
		Calendar: {
			MinSupportedDateTime: "/Date(-62135578800000)/",
			MaxSupportedDateTime: "/Date(253402300799999)/",
			AlgorithmType: 1,
			CalendarType: 1,
			Eras: "1",
			TwoDigitYearMax: 2029,
			IsReadOnly: true
		},
		DateSeparator: "/",
		FirstDayOfWeek: 0,
		CalendarWeekRule: 0,
		FullDateTimePattern: "dddd, MMMM d, yyyy h:mm:ss tt",
		LongDatePattern: "dddd, MMMM d, yyyy",
		LongTimePattern: "h:mm:ss tt",
		MonthDayPattern: "MMMM d",
		PMDesignator: "PM",
		RFC1123Pattern: "ddd, dd MMM yyyy HH\u0027:\u0027mm\u0027:\u0027ss \u0027GMT\u0027",
		ShortDatePattern: "M/d/yyyy",
		ShortTimePattern: "h:mm tt",
		SortableDateTimePattern: "yyyy\u0027-\u0027MM\u0027-\u0027dd\u0027T\u0027HH\u0027:\u0027mm\u0027:\u0027ss",
		TimeSeparator: ":",
		UniversalSortableDateTimePattern: "yyyy\u0027-\u0027MM\u0027-\u0027dd HH\u0027:\u0027mm\u0027:\u0027ss\u0027Z\u0027",
		YearMonthPattern: "MMMM yyyy",
		AbbreviatedDayNames: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
		ShortestDayNames: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
		DayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
		AbbreviatedMonthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", ""],
		MonthNames: [
			"January",
			"February",
			"March",
			"April",
			"May",
			"June",
			"July",
			"August",
			"September",
			"October",
			"November",
			"December",
			""
		],
		IsReadOnly: true,
		NativeCalendarName: "Gregorian Calendar",
		AbbreviatedMonthGenitiveNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", ""],
		MonthGenitiveNames: [
			"January",
			"February",
			"March",
			"April",
			"May",
			"June",
			"July",
			"August",
			"September",
			"October",
			"November",
			"December",
			""
		]
	},
	numberFormat: {
		CurrencyDecimalDigits: 2,
		CurrencyDecimalSeparator: ".",
		IsReadOnly: true,
		CurrencyGroupSizes: [3],
		NumberGroupSizes: [3],
		PercentGroupSizes: [3],
		CurrencyGroupSeparator: ",",
		CurrencySymbol: "$",
		NaNSymbol: "NaN",
		CurrencyNegativePattern: 0,
		NumberNegativePattern: 1,
		PercentPositivePattern: 1,
		PercentNegativePattern: 1,
		NegativeInfinitySymbol: "-∞",
		NegativeSign: "-",
		NumberDecimalDigits: 2,
		NumberDecimalSeparator: ".",
		NumberGroupSeparator: ",",
		CurrencyPositivePattern: 0,
		PositiveInfinitySymbol: "∞",
		PositiveSign: "+",
		PercentDecimalDigits: 2,
		PercentDecimalSeparator: ".",
		PercentGroupSeparator: ",",
		PercentSymbol: "%",
		PerMilleSymbol: "‰",
		NativeDigits: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
		DigitSubstitution: 1
	}
};
